service: myapp

app: myapp
org: saharbit

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: "webpack.config.js"
    includeModules: true
    packager: "yarn"
    excludeFiles: src/**/*.test.js

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  graphql:
    handler: handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
